dist: trusty
sudo: false
language: go
go:
- 1.8.1

install:
- go get github.com/kardianos/govendor

script:
- make test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
